session_name: database
windows:
  - window_name: main
    layout: 406d,85x48,0,0[85x32,0,0,0,85x15,0,33,30]
    options:
      main-pane-height: 80
    shell_command_before:
      - /usr/bin/fish
      - cd ~/eureciclo/salesops-dw/main-salesops-dw # run as a first command in all panes
    panes:
      - shell_command:
        - nvim # pane no. 1
        focus: true
      - echo second pane # pane no. 2
  - window_name: salesops-dw
    layout: 406d,85x48,0,0[85x32,0,0,0,85x15,0,33,30]
    shell_command_before:
      - /usr/bin/fish
      - cd ~/eureciclo/salesops-dw # run as a first command in all panes
    panes:
      - shell_command:
        - nvim ~/eureciclo/salesops-dw/ # pane no. 1
        focus: true
      - echo second pane # pane no. 2
